apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            value: {{ .Values.database.host }}
          - name: DB_USER
            value: {{ .Values.database.user }}
          - name: DB_PASSWORD
            value: {{ .Values.database.password }}
          - name: DB_NAME
            value: {{ .Values.database.name }}
